title: Oasis

description: >-
  a jekyll site template for Codrops.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Docs settings
collections:
  docs:
    output: true
    permalink: /docs/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
